import { StrictMode, useEffect, useState, type FormEvent } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';
type TreeSummary={id:string;name:string;updatedAt:string;_count:{people:number}};type Person={id:string;name:string;birthDate:string|null;deathDate:string|null;bio:string|null};type Tree={id:string;name:string;people:Person[]};
async function api<T>(url:string,options?:RequestInit):Promise<T>{const response=await fetch(url,{...options,headers:{'Content-Type':'application/json',...options?.headers}});if(!response.ok){const body=await response.json().catch(()=>({}));throw new Error(body.message||'Request failed');}return response.json();}
function App(){
 const [trees,setTrees]=useState<TreeSummary[]>([]),[tree,setTree]=useState<Tree|null>(null),[error,setError]=useState('');const [loading,setLoading]=useState(true);
 const loadTrees=()=>api<TreeSummary[]>('/api/trees').then(setTrees).catch(e=>setError(e.message)).finally(()=>setLoading(false));useEffect(()=>{void loadTrees()},[]);
 async function createTree(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);try{setTree(await api<Tree>('/api/trees',{method:'POST',body:JSON.stringify({name:d.get('treeName'),firstPerson:{name:d.get('personName'),birthDate:d.get('birthDate')||undefined}})}));setError('');}catch(x){setError((x as Error).message)}}
 async function openTree(id:string){try{setTree(await api<Tree>(`/api/trees/${id}`));setError('')}catch(x){setError((x as Error).message)}}
 async function addPerson(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!tree)return;const form=e.currentTarget,d=new FormData(form);try{const p=await api<Person>(`/api/trees/${tree.id}/people`,{method:'POST',body:JSON.stringify({name:d.get('name'),birthDate:d.get('birthDate')||undefined,bio:d.get('bio')||undefined})});setTree({...tree,people:[...tree.people,p]});form.reset()}catch(x){setError((x as Error).message)}}
 if(tree)return <main><header className="topbar"><button className="brand" onClick={()=>{setTree(null);loadTrees()}}><i>K</i> Kinfolk</button><span className="server-pill">● Saved on your server</span></header><section className="hero"><div><small>FAMILY TREE</small><h1>{tree.name}</h1><p>Every branch holds a memory.</p></div><strong>{tree.people.length}<span> people</span></strong></section><section className="tree-space"><div className="tree-art"/><div className="people-grid">{tree.people.map(p=><article className="person" key={p.id}><b>{p.name.split(/\s+/).slice(0,2).map(x=>x[0]).join('')}</b><h2>{p.name}</h2><p>{p.birthDate?new Date(p.birthDate).getUTCFullYear():'?'} — {p.deathDate?new Date(p.deathDate).getUTCFullYear():'present'}</p></article>)}</div></section><form className="add-form" onSubmit={addPerson}><h2>Add a person</h2><input name="name" required maxLength={80} placeholder="Full name"/><input name="birthDate" type="date"/><input name="bio" maxLength={2000} placeholder="A memory or detail"/><button>Add person</button></form>{error&&<p className="error">{error}</p>}</main>;
 return <main className="home"><div className="welcome"><div><small>YOUR STORIES, YOUR FAMILY</small><h1>Keep your family <em>close.</em></h1><p>Private family trees, stored on your own server.</p></div><section className="card"><h2>Create a tree</h2><form onSubmit={createTree}><input name="treeName" required maxLength={80} placeholder="Tree name"/><input name="personName" required maxLength={80} placeholder="First person's name"/><input name="birthDate" type="date"/><button>Create tree</button></form><hr/><h3>Existing trees</h3>{loading?<p>Connecting to server…</p>:trees.length?trees.map(t=><button className="tree-row" key={t.id} onClick={()=>openTree(t.id)}><span>{t.name}</span><small>{t._count.people} people</small></button>):<p>No trees yet.</p>}{error&&<p className="error">{error}</p>}</section></div></main>;
}createRoot(document.getElementById('root')!).render(<StrictMode><App/></StrictMode>);
