import { StrictMode,useEffect,useMemo,useRef,useState,type CSSProperties,type FormEvent } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';
import './status.css';
import './auth.css';

type ParentLink={parentId:string;childId:string;type:string};
type Partnership={partnerAId:string;partnerBId:string;status:string;marriageDate:string|null};
type SiblingLink={siblingAId:string;siblingBId:string;type:string};
type Person={id:string;name:string;birthDate:string|null;deathDate:string|null;bio:string|null;parentLinks:ParentLink[];partnershipsA:Partnership[];partnershipsB:Partnership[];siblingLinksA:SiblingLink[];siblingLinksB:SiblingLink[]};
type Tree={id:string;name:string;backgroundStyle:string;backgroundColor:string;treeColor:string;accentColor:string;people:Person[]};
type TreeSummary={id:string;name:string;_count:{people:number}};
type AuthStatus={setupRequired:boolean;authenticated:boolean;user:{id:string;username:string;role:string}|null};

async function api<T>(url:string,options?:RequestInit):Promise<T>{let response:Response;try{response=await fetch(url,{...options,headers:{'Content-Type':'application/json',...options?.headers}})}catch{throw new Error('Cannot reach the Kinfolk server. Check that Docker services are running and try again.')}if(response.status===204)return undefined as T;if(!response.ok){const body=await response.json().catch(()=>({}));if(response.status===401&&!url.startsWith('/api/auth/'))window.dispatchEvent(new Event('kinfolk:unauthorized'));throw new Error(body.message||`The server returned an error (${response.status}).`)}return response.json()}
const inputDate=(value:string|null)=>value?.slice(0,10)||'';
const year=(value:string|null)=>value?new Date(value).getUTCFullYear():'?';
function Status({message,onRetry}:{message:string;onRetry?:()=>void}){return <div className="status-error" role="alert"><strong>Something went wrong</strong><p>{message}</p>{onRetry&&<button type="button" onClick={onRetry}>Try again</button>}</div>}

function PersonEditor({tree,person,onSaved,onClose}:{tree:Tree;person:Person|null;onSaved:(tree:Tree)=>void;onClose:()=>void}){
 const partnership=person?[...person.partnershipsA,...person.partnershipsB][0]:undefined;
 const partnerId=partnership?(partnership.partnerAId===person?.id?partnership.partnerBId:partnership.partnerAId):'';
 const [selectedPartner,setSelectedPartner]=useState(partnerId);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 const others=tree.people.filter(p=>p.id!==person?.id);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const d=new FormData(e.currentTarget);const body={name:d.get('name'),birthDate:d.get('birthDate')||undefined,deathDate:d.get('deathDate')||undefined,bio:d.get('bio')||undefined,parentIds:[d.get('parent1'),d.get('parent2')].filter(Boolean),partnerId:d.get('partnerId')||undefined,partnershipStatus:d.get('partnershipStatus'),marriageDate:d.get('marriageDate')||undefined,siblingId:d.get('siblingId')||undefined,siblingType:d.get('siblingType')};try{onSaved(await api<Tree>(person?`/api/people/${person.id}`:`/api/trees/${tree.id}/people`,{method:person?'PATCH':'POST',body:JSON.stringify(body)}));onClose()}catch(x){setError((x as Error).message);setBusy(false)}}
 async function remove(){if(!person||!confirm(`Remove ${person.name} from this tree?`))return;setBusy(true);setError('');try{await api(`/api/people/${person.id}`,{method:'DELETE'});onSaved(await api<Tree>(`/api/trees/${tree.id}`));onClose()}catch(x){setError((x as Error).message);setBusy(false)}}
 return <div className="overlay"><form className="modal" onSubmit={submit}><header><div><small>{person?'EDIT RELATIVE':'NEW RELATIVE'}</small><h2>{person?'Edit person':'Add a person'}</h2></div><button type="button" className="close" onClick={onClose}>×</button></header><div className="form-grid"><label className="full">Full name *<input name="name" required maxLength={80} defaultValue={person?.name}/></label><label>Birth date<input name="birthDate" type="date" defaultValue={inputDate(person?.birthDate||null)}/></label><label>Death date<input name="deathDate" type="date" defaultValue={inputDate(person?.deathDate||null)}/></label><h3 className="full">Parents</h3><label>Parent 1<select name="parent1" defaultValue={person?.parentLinks[0]?.parentId||''}><option value="">Unknown</option>{others.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Parent 2<select name="parent2" defaultValue={person?.parentLinks[1]?.parentId||''}><option value="">Unknown</option>{others.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><h3 className="full">Couple</h3><label>Spouse or partner<select name="partnerId" value={selectedPartner} onChange={e=>setSelectedPartner(e.target.value)}><option value="">None</option>{others.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Status<select name="partnershipStatus" defaultValue={partnership?.status||'partnered'} disabled={!selectedPartner}><option value="partnered">Partners</option><option value="married">Married</option></select></label><label>Marriage date<input name="marriageDate" type="date" defaultValue={inputDate(partnership?.marriageDate||null)} disabled={!selectedPartner}/></label><span/><h3 className="full">Add a sibling connection</h3><label>Sibling<select name="siblingId"><option value="">None</option>{others.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Type<select name="siblingType" defaultValue="sibling"><option value="sibling">Sibling</option><option value="full">Full sibling</option><option value="half">Half sibling</option><option value="step">Step-sibling</option><option value="adopted">Adopted sibling</option></select></label><label className="full">About<textarea name="bio" rows={3} maxLength={2000} defaultValue={person?.bio||''}/></label></div>{error&&<p className="error">{error}</p>}<footer>{person&&<button type="button" className="danger" onClick={remove}>Delete</button>}<span/><button type="button" className="secondary" onClick={onClose}>Cancel</button><button>Save person</button></footer></form></div>
}

function DesignEditor({tree,onSaved,onClose}:{tree:Tree;onSaved:(tree:Tree)=>void;onClose:()=>void}){const [busy,setBusy]=useState(false),[error,setError]=useState('');async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;setBusy(true);setError('');const d=new FormData(e.currentTarget);try{onSaved(await api<Tree>(`/api/trees/${tree.id}`,{method:'PATCH',body:JSON.stringify(Object.fromEntries(d))}));onClose()}catch(x){setError((x as Error).message);setBusy(false)}}return <div className="overlay"><form className="modal design" onSubmit={submit}><header><div><small>TREE APPEARANCE</small><h2>Design your tree</h2></div><button type="button" className="close" onClick={onClose} disabled={busy}>×</button></header><div className="form-grid"><label className="full">Style<select name="backgroundStyle" defaultValue={tree.backgroundStyle} disabled={busy}><option value="botanical">Botanical</option><option value="classic">Classic</option><option value="minimal">Minimal</option></select></label><label>Background<input name="backgroundColor" type="color" defaultValue={tree.backgroundColor} disabled={busy}/></label><label>Tree and links<input name="treeColor" type="color" defaultValue={tree.treeColor} disabled={busy}/></label><label>Couple accent<input name="accentColor" type="color" defaultValue={tree.accentColor} disabled={busy}/></label></div>{error&&<Status message={error}/>}<footer><span/><button type="button" className="secondary" onClick={onClose} disabled={busy}>Cancel</button><button disabled={busy}>{busy?'Saving…':'Save design'}</button></footer></form></div>}

function TreeView({tree,onEdit}:{tree:Tree;onEdit:(person:Person)=>void}){
 const treeRef=useRef<HTMLElement>(null);const [paths,setPaths]=useState<string[]>([]);
 const generations=useMemo(()=>{const cache=new Map<string,number>();const base=(p:Person,trail=new Set<string>()):number=>{if(cache.has(p.id))return cache.get(p.id)!;if(trail.has(p.id)||!p.parentLinks.length)return 0;const next=new Set(trail).add(p.id);const parents=p.parentLinks.map(l=>tree.people.find(x=>x.id===l.parentId)).filter(Boolean) as Person[];const value=parents.length?Math.max(...parents.map(x=>base(x,next)))+1:0;cache.set(p.id,value);return value};const gen=(p:Person)=>{const link=[...p.partnershipsA,...p.partnershipsB][0];const partner=link&&tree.people.find(x=>x.id===(link.partnerAId===p.id?link.partnerBId:link.partnerAId));return Math.max(base(p),partner?base(partner):0)};const map=new Map<number,Person[]>();tree.people.forEach(p=>{const n=gen(p);map.set(n,[...(map.get(n)||[]),p])});return [...map.entries()].sort(([a],[b])=>a-b)},[tree]);
 useEffect(()=>{const draw=()=>{const root=treeRef.current;if(!root)return;const box=root.getBoundingClientRect(),next:string[]=[];tree.people.forEach(child=>child.parentLinks.forEach(link=>{const parent=root.querySelector<HTMLElement>(`[data-person="${CSS.escape(link.parentId)}"]`),target=root.querySelector<HTMLElement>(`[data-person="${CSS.escape(child.id)}"]`);if(!parent||!target)return;const a=parent.getBoundingClientRect(),b=target.getBoundingClientRect(),x1=a.left-box.left+a.width/2,y1=a.bottom-box.top,x2=b.left-box.left+b.width/2,y2=b.top-box.top,mid=y1+(y2-y1)/2;next.push(`M ${x1} ${y1} V ${mid} H ${x2} V ${y2}`)}));setPaths(next)};requestAnimationFrame(draw);window.addEventListener('resize',draw);return()=>window.removeEventListener('resize',draw)},[tree]);
 const card=(p:Person)=><button className="person-card" data-person={p.id} key={p.id} onClick={()=>onEdit(p)}><b>{p.name.split(/\s+/).slice(0,2).map(x=>x[0]).join('')}</b><h3>{p.name}</h3><p>{year(p.birthDate)} — {p.deathDate?year(p.deathDate):'present'}</p>{p.parentLinks.length>0&&<small>Child of {p.parentLinks.map(l=>tree.people.find(x=>x.id===l.parentId)?.name.split(' ')[0]).filter(Boolean).join(' & ')}</small>}</button>;
 return <section ref={treeRef} className={`tree-space ${tree.backgroundStyle}`} style={{'--tree-bg':tree.backgroundColor,'--tree-color':tree.treeColor,'--accent':tree.accentColor} as CSSProperties}><div className="tree-art"/><svg aria-hidden="true" style={{position:'absolute',inset:0,width:'100%',height:'100%',overflow:'visible',pointerEvents:'none'}}>{paths.map((path,index)=><path d={path} key={index} fill="none" stroke={tree.treeColor} strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>)}</svg>{generations.map(([n,people])=>{const rendered=new Set<string>();return <div className="generation" key={n}>{people.map(p=>{if(rendered.has(p.id))return null;const link=[...p.partnershipsA,...p.partnershipsB][0];const partner=link&&people.find(x=>x.id===(link.partnerAId===p.id?link.partnerBId:link.partnerAId));rendered.add(p.id);if(partner){rendered.add(partner.id);return <div className="couple" key={p.id}>{card(p)}<span>{link.marriageDate?`Married ${new Date(link.marriageDate).toLocaleDateString()}`:'Partners'}</span>{card(partner)}</div>}return card(p)})}</div>})}</section>
}

function KinfolkApp({username,onLogout,logoutBusy}:{username:string;onLogout:()=>void;logoutBusy:boolean}){
 const [trees,setTrees]=useState<TreeSummary[]>([]),[tree,setTree]=useState<Tree|null>(null),[editor,setEditor]=useState<Person|null|false>(false),[design,setDesign]=useState(false),[error,setError]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false);
 async function load(){setLoading(true);setError('');try{setTrees(await api<TreeSummary[]>('/api/trees'))}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const d=new FormData(e.currentTarget);try{setTree(await api<Tree>('/api/trees',{method:'POST',body:JSON.stringify({name:d.get('treeName'),firstPerson:{name:d.get('personName'),birthDate:d.get('birthDate')||undefined}})}))}catch(x){setError((x as Error).message)}finally{setBusy(false)}}
 async function open(id:string){setBusy(true);setError('');try{setTree(await api<Tree>(`/api/trees/${id}`))}catch(x){setError((x as Error).message)}finally{setBusy(false)}}
 if(!tree)return <main className="home"><div className="welcome"><div><small>YOUR STORIES, YOUR FAMILY</small><h1>Keep your family <em>close.</em></h1><p>Private family trees, stored on your own server.</p></div><section className="card"><h2>Create a tree</h2><form onSubmit={create}><input name="treeName" required placeholder="Tree name" disabled={busy}/><input name="personName" required placeholder="First person's name" disabled={busy}/><input name="birthDate" type="date" disabled={busy}/><button disabled={busy}>{busy?'Working…':'Create tree'}</button></form><hr/><h3>Existing trees</h3>{loading?<div className="loading-state"><span/><p>Connecting to your server…</p></div>:error?<Status message={error} onRetry={()=>void load()}/>:trees.length?trees.map(t=><button className="tree-row" key={t.id} onClick={()=>void open(t.id)} disabled={busy}><span>{t.name}</span><small>{t._count.people} people</small></button>):<div className="empty-message"><strong>No trees yet</strong><p>Create your first tree using the form above.</p></div>}</section></div></main>;
 return <main><header className="topbar"><button className="brand" onClick={()=>{setTree(null);void load()}}><i>K</i> Kinfolk</button><nav><button className="secondary" onClick={()=>setDesign(true)}>Design</button><button onClick={()=>setEditor(null)}>＋ Add person</button><button className="auth-logout secondary" onClick={onLogout} disabled={logoutBusy}>Sign out · {username}</button></nav></header><section className="hero"><div><small>FAMILY TREE</small><h1>{tree.name}</h1><p>Every branch holds a memory.</p></div><strong>{tree.people.length}<span> people</span></strong></section>{tree.people.length?<TreeView tree={tree} onEdit={p=>setEditor(p)}/>:<section className="tree-space empty-tree"><strong>This tree is ready to grow</strong><p>Add its first person to begin.</p><button onClick={()=>setEditor(null)}>Add first person</button></section>}{editor!==false&&<PersonEditor tree={tree} person={editor} onSaved={setTree} onClose={()=>setEditor(false)}/>} {design&&<DesignEditor tree={tree} onSaved={setTree} onClose={()=>setDesign(false)}/>}</main>
}

function App(){
 const [status,setStatus]=useState<AuthStatus|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function refresh(){setError('');try{setStatus(await api<AuthStatus>('/api/auth/status'))}catch(x){setError((x as Error).message)}}
 useEffect(()=>{void refresh();const expired=()=>void refresh();window.addEventListener('kinfolk:unauthorized',expired);return()=>window.removeEventListener('kinfolk:unauthorized',expired)},[]);
 async function authenticate(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const d=new FormData(e.currentTarget),password=String(d.get('password')||'');if(status?.setupRequired&&password!==d.get('confirmPassword')){setError('The passwords do not match.');setBusy(false);return}try{await api(status?.setupRequired?'/api/auth/setup':'/api/auth/login',{method:'POST',body:JSON.stringify({username:d.get('username'),password})});await refresh()}catch(x){setError((x as Error).message)}finally{setBusy(false)}}
 async function logout(){setBusy(true);try{await api('/api/auth/logout',{method:'POST'});await refresh()}finally{setBusy(false)}}
 if(!status)return <main className="auth-page"><div className="loading-state"><span/><p>{error?'Unable to connect':'Checking server security…'}</p>{error&&<Status message={error} onRetry={()=>void refresh()}/>}</div></main>;
 if(!status.authenticated)return <main className="auth-page"><section className="auth-card"><div className="auth-brand"><i>K</i><strong>Kinfolk</strong></div><small>{status.setupRequired?'FIRST-RUN SETUP':'PRIVATE FAMILY TREE'}</small><h1>{status.setupRequired?'Create your administrator':'Welcome back'}</h1><p>{status.setupRequired?'This account will protect every family tree stored on this server.':'Sign in to access the family trees on this server.'}</p><form onSubmit={authenticate}><label>Username<input name="username" required minLength={status.setupRequired?3:1} maxLength={40} autoComplete="username" pattern={status.setupRequired?'[A-Za-z0-9._-]+':undefined} disabled={busy}/></label><label>Password<input name="password" type="password" required minLength={status.setupRequired?12:1} maxLength={128} autoComplete={status.setupRequired?'new-password':'current-password'} disabled={busy}/></label>{status.setupRequired&&<label>Confirm password<input name="confirmPassword" type="password" required minLength={12} maxLength={128} autoComplete="new-password" disabled={busy}/></label>}{error&&<Status message={error}/>}<button disabled={busy}>{busy?'Please wait…':status.setupRequired?'Create administrator':'Sign in'}</button></form>{status.setupRequired&&<p className="auth-note">Use at least 12 characters and store the password securely. Kinfolk cannot recover it for you.</p>}</section></main>;
 return <KinfolkApp username={status.user?.username||'admin'} onLogout={()=>void logout()} logoutBusy={busy}/>
}

createRoot(document.getElementById('root')!).render(<StrictMode><App/></StrictMode>);
