import type { Person, Tree } from '../types';
import { displayDate } from '../format';
import { eventLabel } from './LifeEventManager';

export function PersonDetails({tree,person,onEdit,onClose}:{tree:Tree;person:Person;onEdit:()=>void;onClose:()=>void}){
 const names=(ids:string[])=>ids.map(id=>tree.people.find(candidate=>candidate.id===id)?.name).filter(Boolean).join(', ');
 const parents=names(person.parentLinks.map(link=>link.parentId));
 const partnership=[...person.partnershipsA,...person.partnershipsB][0];
 const partner=partnership&&tree.people.find(candidate=>candidate.id===(partnership.partnerAId===person.id?partnership.partnerBId:partnership.partnerAId));
 const siblings=names([...person.siblingLinksA,...person.siblingLinksB].map(link=>link.siblingAId===person.id?link.siblingBId:link.siblingAId));
 const timeline=[...(person.birthDate||person.birthPlace?[{type:'Birth',date:person.birthDate,place:person.birthPlace,description:null}]:[]),...person.lifeEvents.map(event=>({type:eventLabel(event.type),date:event.date,place:event.place,description:event.description})),...(person.deathDate||person.deathPlace?[{type:'Death',date:person.deathDate,place:person.deathPlace,description:null}]:[])].sort((left,right)=>(left.date||'9999').localeCompare(right.date||'9999'));
 return <div className="overlay"><article className="modal person-details"><header><div><small>PERSON DETAILS</small><h2>{person.name}</h2>{person.maidenName&&<p>Born {person.maidenName}</p>}</div><button type="button" className="close" onClick={onClose}>×</button></header><div className="detail-facts"><div><span>Born</span><strong>{person.birthDate?displayDate(person.birthDate):'Unknown date'}</strong>{person.birthPlace&&<p>{person.birthPlace}</p>}</div><div><span>Died</span><strong>{person.deathDate?displayDate(person.deathDate):'Living or unknown'}</strong>{person.deathPlace&&<p>{person.deathPlace}</p>}</div></div>{person.bio&&<section className="detail-section"><h3>About</h3><p>{person.bio}</p></section>}<section className="detail-section"><h3>Relationships</h3><dl>{parents&&<><dt>Parents</dt><dd>{parents}</dd></>}{partner&&<><dt>{partnership?.status==='married'?'Spouse':'Partner'}</dt><dd>{partner.name}{partnership?.marriageDate?` · Married ${displayDate(partnership.marriageDate)}`:''}</dd></>}{siblings&&<><dt>Siblings</dt><dd>{siblings}</dd></>}</dl>{!parents&&!partner&&!siblings&&<p>No relationships recorded.</p>}</section><section className="detail-section"><h3>Life timeline</h3>{timeline.length?<ol className="life-timeline">{timeline.map((event,index)=><li key={`${event.type}-${event.date||index}-${index}`}><time>{event.date?displayDate(event.date):'Date unknown'}</time><div><strong>{event.type}</strong>{event.place&&<p>{event.place}</p>}{event.description&&<p>{event.description}</p>}</div></li>)}</ol>:<p>No life events recorded.</p>}</section><footer><span/><button type="button" className="secondary" onClick={onClose}>Close</button><button type="button" onClick={onEdit}>Edit person</button></footer></article></div>
}
